# Generated by Django 4.2.6 on 2023-12-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accessrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecords',
            new_name='AccessRecord',
        ),
    ]
